dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
  - smartcontractkit/chainlink@1.0.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
      - "@chainlink=smartcontractkit/chainlink@1.0.1"

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
