# Generated by Django 4.0.1 on 2022-02-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('im', models.ImageField(upload_to='', verbose_name='media')),
            ],
        ),
    ]
