# Generated by Django 4.0.1 on 2022-02-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='im',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
