# Generated by Django 4.0.1 on 2022-02-05 13:06

from django.db import migrations, models
import nft.models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_alter_image_im'),
    ]

    operations = [
        migrations.CreateModel(
            name='nft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('nft_file', models.FileField(upload_to=nft.models.name_file)),
            ],
        ),
    ]
