# Generated by Django 4.0.1 on 2022-02-06 06:42

from django.db import migrations, models
import nft.models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_nft'),
    ]

    operations = [
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('metadata_file', models.FileField(upload_to=nft.models.name_file)),
            ],
        ),
    ]
