# Generated by Django 4.0.1 on 2022-02-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='metadata_file',
        ),
    ]
