# Generated by Django 4.0.1 on 2022-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0007_nft_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft_collection',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
