# Generated by Django 4.0.1 on 2022-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0008_alter_nft_collection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='nft_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('metadataURL', models.URLField()),
                ('collection', models.CharField(max_length=100)),
                ('on_sale', models.BooleanField()),
                ('is_minted', models.BooleanField()),
                ('price', models.FloatField()),
                ('contract_address', models.CharField(max_length=50)),
                ('token_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='nft_collection',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
