# Generated by Django 4.0.1 on 2022-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0009_nft_asset_alter_nft_collection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft_collection',
            name='contract',
            field=models.CharField(default='0x', max_length=50),
        ),
    ]
