# Generated by Django 4.0.1 on 2022-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoassets', '0002_remove_profile_id_alter_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.URLField(default='https://ipfs.io/ipfs/QmPPpYeRvxRitriYWLh532hjgkUffesbCwshRnQppwmtHv?filename=Beyonce.jpg'),
        ),
    ]
