# Generated by Django 4.0.1 on 2022-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoassets', '0003_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Coolest guy ever.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Nameless Hero', max_length=50),
        ),
    ]
