# Generated by Django 4.0.1 on 2022-02-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoassets', '0004_profile_description_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='erc721contracts',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('first_token_URI', models.CharField(max_length=100)),
            ],
        ),
    ]
