# Generated by Django 4.0.1 on 2022-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoassets', '0005_erc721contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='erc721contracts',
            name='block',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
