# Generated by Django 4.0.1 on 2022-02-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoassets', '0006_erc721contracts_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='blocks_scanned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_block', models.IntegerField()),
                ('end_block', models.IntegerField()),
            ],
        ),
    ]
